### ISSUE TITLE
Where is D-NER architecture in the E2E_NER code?

### ISSUE THREAD

**Issue by FriedaSmith** [raotnameh/E2E_NER-Through-Speech#4]
I'm sorry to trouble you, but where is `D-NER architecture` in the E2E_NER code or how to add `special symbols (’{’,’|’, ’$’)` to the recognition result?

**Comment by raotnameh** [comment]
@FriedaSmith The labels.json file already has special symbols. To create the D-NER architecture just use the lables.json file.

**Comment by FriedaSmith** [comment]
Sorry, maybe I didn't make myself clear. I want to know which class is implement of  the code `My name is Gaurav Yadav` to `My name is <PER>`. How to recognize named entities with LM? When ` --lm-path=None`, it can also recognize named entities.

**Comment by raotnameh** [comment]
@FriedaSmith Currently, to train the LM we do not replace the name with a <per> token, instead, we train our LM with the special tokens denoting the start and end in the text itself.

Steps to train the LM: 
reference sentence = my name is Gaurav Yadav.
the sentence used to train the LM = MY NAME IS |GAURAV YADAV] **instead** of MY NAME IS <PER>.

Thus you can either use the LM provided by us in the lm folder or train an LM after pre-processing the named entities in your own data.

Furthermore,  when the argument --lm-path = None, the model outputs the special tokens because it is part of the softmax layer. If you want the output without, write a script to remove these characters.

 Replacing a named entity with a token is for future work.

**Comment by FriedaSmith** [comment]
@raotnameh Line 54: Is named entities recognization's result, `MY NAME IS |GAURAV YADAV]` ,  implemented directly by loading the model? such as,  `out, output_sizes = model(spect, input_sizes)` in `transcribe.py` line: 54.

**Comment by raotnameh** [comment]
@FriedaSmith Yes, the model outputs the result with named entities directly. But to get even better results we have to use an LM.

**Comment by FriedaSmith** [comment]
Thank you very much.
