### ISSUE TITLE
Questions on the data used in the E2E NER paper

### ISSUE THREAD

**Issue by faraazn** [raotnameh/E2E_NER-Through-Speech#9]
Congrats again on the paper!  We had a few questions about data2. They relate to the analysis done in the doc here: https://docs.google.com/document/d/1zitwIAgVKcypQ41XYDBYf9yvodgeWJZrnIIuz-hhmYU/edit?usp=sharing

In the paper, you mention that you used a pretrained tagger to identify sentences that were likely to have entities. However, it seems that the selected sentences are not very consistent across the datasets. For example, in Librispeech, sentences with common names such as Henry, John, James, etc. are not included, but in Vox/CV, sentences with uncommon names such as Basset, Hughie, Vincent, and Ogilvy are included. Were there any additional steps taken before/after using the pretrained tagger to get from data1 to data2?

Next, it seems as though there are a number of incorrectly labeled entities that occur with relatively high frequency. Looking at the top 20 labeled entities per category, “I’m” “I’ll” and “You’ll” are labeled as person entities, “US” is sometimes labeled as a location when it is referring to the pronoun, and “it’s” “falcon” and “yorkshire” are labeled as organization entities. Do you know how these annotation errors may have occurred, and is there a plan to release fixes for them?

**Comment by raotnameh** [comment]
Hi @faraazn 

The pre-trained NER tagger is used off the shelf from [flair](https://github.com/flairNLP/flair). There was no pre-processing step. The inconsistency is because of the NER tagger is a DL based and thus stochastic in nature. 

In data2, there are two splits: repeated and unique sentences. In the unique sentences the stats are: 
[('TOM', 208),
 ('ANNE', 192),
 ('MARGARET', 172),
 ('MARY', 168),
 ('GOD', 163),
 ('JOHN', 153),
 ('PETER', 151),
 ('DICK', 106),
 ('JACK', 97),
 ('GEORGE', 89),
 ('DAVID', 87),
 ('ELSIE', 86),
 ('CHRIS', 81),
 ('ALICE', 80),
 ('ARTHUR', 76),
 ('EDWARD', 75),
 ('HENRY', 74),
 ('PHILIP', 74),
 ('JESUS', 73),
 ('JANE', 73)................]

First, we annotated the data and,  secondly, we found matching sentences to increase the dataset size. The second part is responsible for the increase in the count of ("I'M", 49) and ("I'LL", 38)  which was originally insignificant. So, to avoid this you can remove the repeated sentences. These were introduced as random noise in the data such that the DL model does not overfit. If you do not want them, please go through them manually and remove them and also open a pull request to add the list of these tokens. That would be very helpful.

“US” is sometimes labelled as a location when it is referring to the pronoun, and “it’s” “falcon” and “yorkshire” are labelled as organization entities: For these, it is what the annotator seemed appropriate at the time given the sentence. Treat it as Annotator bias.


I hope this answers your questions.
